#!/usr/bin/env ruby
require 'json'
require 'pry'

require_relative 'lib/data_ingestor'
require_relative 'lib/helpers'
include Helpers

usage = %q(
  Usage:
  main {api url} {api key}

  Example:
  $ ./main http://localhost:9292 myapikey
)

# Respond with the help info if no arguments or the help flag is passed
if ARGV.empty? || ARGV[ 0 ] == '--help' || ARGV[ 0 ] == '-h'
  puts usage
  exit
end

ingestor = DataIngestor.new( ARGV[ 0 ], ARGV[ 1 ] )

parsed_data = ingestor.ingest_and_parse

flattened_orgs = []

parsed_data.map do | top_org | 
  flattened_orgs += top_org.flatten
end

json = org_objects_to_json( flattened_orgs )

File.open( "flattened_orgs.json", "w" ) do | file |
  file.write( json )
end

puts "*******************************************"
puts "Successfully ingested and JSON file written"
puts "*******************************************"
